- name: configure frotntend server
  hosts: frontend
  tasks:
  - name: disable default nginx
    ansible.builtin.command: dnf module disable nginx -y
  - name: enable nginx 1.20 
    ansible.builtin.command: dnf module enable nginx:1.24 -y
  
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove default html package
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html package
    ansible.builtin.file:
      path: /user/share/nginx/html
      state: directory

  - name: download code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      path: /tmp/frontend..zip     

  - name: unarchive code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html

  - name: copy conf file
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted        

