- name: configure frontend
  hosts: frontend
  become: yes
  tasks:
  - name: disable default nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes    

  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: present

  - name: download code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unarchive frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /etc/usr/share/nginx/html

  - name: remove conf file content
    ansible.builtin.file:
      path: /etc.nginx.conf
      state: absent

  - name: creste conf file content
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted


