[frontend]
frontend.sivadaws.online
[mongodb]
mongodb.sivadaws.online
[catalogue]
catalogue.sivadaws.online
[redis]
redis.sivadaws.online
[user]
user.sivadaws.online
[cart]
cart.sivadaws.online

[local]
localhost