; [frontend]
; frontend.sivadaws.online
[mongodb]
98.92.220.84
; [catalogue]
; catalogue.sivadaws.online
; [redis]
; redis.sivadaws.online
; [user]
; user.sivadaws.online
; [cart]
; cart.sivadaws.online
; [mysql]
; mysql.sivadaws.online
; [rabbitmq]
; rabbitmq.sivadaws.online

[local]
localhost