[frontend]
18.212.94.206
[mongodb]
204.236.198.113
[catalogue]
3.91.50.94
; [redis]
; redis.sivadaws.online
; [user]
; user.sivadaws.online
; [cart]
; cart.sivadaws.online
; [mysql]
; mysql.sivadaws.online
; [rabbitmq]
; rabbitmq.sivadaws.online

[local]
localhost