- name: configure mongodb server
  hosts: mongodb
  tasks:
  - name: enable mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb    
    ansible.builtin.package:
      name: mongodb-org
      state: install
  - name: start mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes    
  - name: enable reomte access
    ansible.builtin.replace:
      regexp: '127.0.0.0'
      replace: '0.0.0.0'
      path: /etc/mongo.conf
  - name: restart mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted    