- name: Variabes info
  hosts: local
  connection: local
  vars:
    COURSE: ansible
    DURATION: 10hr
    TRAINER: Sivakumar
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }} course duration {{ DURATION }}, Trainer {{ TRAINER }}"

- name: prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: plrase enter name
  tasks:  
  ansible.builtin.debug:
    msg: "{{ USERNAME }}"
  









# - name: print details
#   hosts: local
#   connection: local
#   tasks:
#   - name: print name
#     ansible.builtin.debug:
#       msg: "Hello world"


# - name: Install nginx server
#   hosts: frontend
#   become: yes
#   tasks:
#   - name: install nginx
#     ansible.builtin.package:
#       name: nginx
#       state: installed
#   - name: enable and start nginx
#     ansible.builtin.service:
#       name: nginx
#       status: started
#       enabled: yes
