- name: configure rabbit mq server
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install rabbitma server
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present

  - name: start and enable
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes        
